version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.github/src/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/aws/api/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/aws/eks/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/aws/s3/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/aws/ecr/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/aws/lambda/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/aws/secrets_manager/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/aws/vpc/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/aws/src/"
    schedule:
      interval: "weekly"
