name: Terraform-Checks

on:
  push:
    branches:
      - main

jobs:
  terraform-check-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Terraform Format
        run: terraform fmt -check -diff

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.3'

      - name: Get test dependencies
        working-directory: terratests
        run: go get -t ./...

      - name: Install Go dependencies
        working-directory: terratests
        run: go mod tidy

      - name: Run Terratest
        working-directory: terratests
        run: go test -v
